config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    get '/representatives/:representative_id', to: 'representatives#show', as: 'representative'
    resources :representatives, only: [:index]
    resources :representatives do
        resources :news_items, only: %i[index show]
        get 'show'
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
                                                                      via: [:post]
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
    end
    get '/search/(:address)' => 'search#search', :as => 'search_representatives'

    # Routes for Finance
    get '/finances', to: 'finances#index', :as => 'finances'
    get '/finances/search', to: 'finances#search', :as => 'search_finances'
  
end

app/models/representative.rb
# frozen_string_literal: true

class Representative < ApplicationRecord
  has_many :news_items, dependent: :delete_all

  def self.civic_api_to_representative_params(rep_info)
    reps = []

    rep_info.officials.each_with_index do |official, index|
      rep_params = { name: official.name, ocdid: '', party: '', photo_url: '',
          zip: '', address: '', city: '', state: '' }

      rep_info.offices.each do |office|
        if office.official_indices.include? index
          rep_params[:title] = office.name
          rep_params[:ocdid] = office.division_id
        end
        create_address(rep_params, official)

        rep_params[:photo_url] = official.photo_url if official.instance_variable_defined?(:@photo_url)
        rep_params[:party] = official.party if official.instance_variable_defined?(:@party)
      end

      representative = create_rep(rep_params)
      reps.push(representative)
    end

    reps
  end

  def self.create_address(rep_params, official)
    return if official.address.nil?

    rep_params[:address] = official.address[0].line1
    rep_params[:city] = official.address[0].city
    rep_params[:state] = official.address[0].state
    rep_params[:zip] = official.address[0].zip
  end

  def self.create_rep(rep_params)
    representative = Representative.find_or_initialize_by(name: rep_params[:name], ocdid: rep_params[:ocdid])
    if representative.new_record?
      representative = Representative.create!(rep_params)
      representative.save!
    end
    representative
  end
end

app/controllers/representatives_controller.rb
# frozen_string_literal: true

class RepresentativesController < ApplicationController
  def index
    @representatives = Representative.all
  end

  def show
    @representative = Representative.find params[:representative_id]
  end
end

app/helpers/representatives_helper.rb
# frozen_string_literal: true

module RepresentativesHelper
end

app/views/representatives/index.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Search for a Representative

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = form_tag search_representatives_path, method: :get do
            .form-group.row
                .col-md-4
                    %label.col-form-label
                        Enter a location:
                .col-md-6
                    = text_field_tag(:address, nil, class: 'form-control')

            .actions
                = submit_tag 'Search', class: 'btn btn-primary'

app/views/representatives/search.html.haml
.container-fluid
    .row
        .col-md-8.offset-md-2
            .table-responsive-md.pt-5
                %table.table.table-striped.table-hover#events
                    %caption Table of Representatives
                    %thead.thead-dark
                        %tr
                            %th Name
                            %th Office
                            %th Links
                    %tbody
                        - @representatives.each_with_index do |rep, _index|
                            %tr
                                %td
                                    = link_to rep.name, representative_show_path(rep.id)
                                %td= rep.title
                                %td
                                    = link_to representative_news_items_path(rep.id), class: 'btn btn-primary' do
                                        %i.fas.fa-newspaper
                                        News Articles

app/views/representatives/show.html.haml
.container
    .row.mt-5
        .col-12.text-center
            %h2
                %strong
                    = @representative.name.to_s

    .row.mt-3
        .col-12.text-center
            %img{ src: @representative.photo_url, alt: 'Representative Photo', class: 'img-fluid rounded-circle' }

    .row.mt-3
        .col-12.text-center
            %p
                %strong
                    Office:
                = @representative.title.to_s

    .row.mt-3
        .col-12.text-center
            %p
                %strong
                    OCDID:
                = @representative.ocdid.to_s

    .row.mt-3
        .col-12.text-center
            %p
                %strong
                    Contact Address:
                #{@representative.address}, #{@representative.city}, #{@representative.state}, #{@representative.zip}

    .row.mt-3
        .col-12.text-center
            %p
                %strong
                    Political Party:
                = @representative.ocdid.to_s